name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go (if building a Go project)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' # Specify your Go version

      # Build the project
      - name: Build executable
        run: |
          go build -o denote

      # Archive the build artifact
      - name: Create release artifact
        run: |
          zip denote.zip denote
        shell: bash

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: denote
          path: denote.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a GitHub release
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}

      # Upload the artifact to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: myapp.zip
          asset_name: myapp.zip
          asset_content_type: application/zip
