name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)
permissions:
  packages: write
  contents: write
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go (if building a Go project)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' # Specify your Go version

      # Build the project
      - name: Build executable
        run: |
          go build -o denote
        env:
          GOOS: darwin
          GOARCH: amd64

      # Archive the build artifact
      - name: Create release artifact
        run: |
          zip denote.zip denote
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            denote.zip
